---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: test
  name: MAGIC-USER-reads-all-pods
subjects:
  - kind: User
    name: MAGIC_USER
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: all-pod-access
  apiGroup: rbac.authorization.k8s.io

