---
apiVersion: v1
kind: Pod
metadata:
  name: simple-nginx
  namespace: scrumteam-one
  labels:
    app: simple-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: CURRENT_VERSION
        value: 0.0.9
